version: "3.9"

services:
  redis:
    image: redis:7.0-alpine
    ports:
    - 6379
    command: redis-server --save 20 1 --loglevel warning --requirepass R3d1s
    volumes:
    - redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 3

  gateway:
    image: kong:2.8.1-alpine
    ports:
    - 80:8000
    - 8001:8001
    environment:
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_LISTEN=0.0.0.0:8001
    - KONG_DATABASE=off
    - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yaml
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_PROXY_LISTEN=0.0.0.0:8000
    volumes:
    - ./gateway:/kong/declarative/

  auth:
    image: gr4vy.dev/auth
    ports:
    - 5000
    environment:
    - HTTP_PORT=5000
    - JWT_SECRET=s3cr3t
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s

  core:
    depends_on:
    - redis
    image: gr4vy.dev/core
    ports:
    - 5000
    environment:
    - HTTP_PORT=5000
    - REDIS_URL=redis://:R3d1s@redis:6379/0
    - JWT_SECRET=s3cr3t
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s

  psp:
    depends_on:
    - redis
    image: gr4vy.dev/psp
    environment:
    - REDIS_URL=redis://:R3d1s@redis:6379/0

volumes:
  redis:
    driver: local
